# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      chmod -R 777  ./
      docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-api-scan.py -t http://jv-dds-ccs-sit.anteraja.id/rest/speedQuery/waybill/byNo/web -f openapi -g api-scan.conf -x OWASP-ZAP-Report.xml -r api-scan-report.html -J api-report.json 
      
      true
      
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $XslPath = "$(System.DefaultWorkingDirectory)/OWASPToNUnit3.xslt"
      $XmlInputPath = "$(System.DefaultWorkingDirectory)/OWASP-ZAP-Report.xml"
      $XmlOutputPath = "$(System.DefaultWorkingDirectory)/Converted-OWASP-ZAP-Report.xml"
      $XslTransform = New-Object System.Xml.Xsl.XslCompiledTransform
      $XslTransform.Load($XslPath)
      $XslTransform.Transform($XmlInputPath, $XmlOutputPath)
- task: publishhtmlreport@1
  inputs:
    htmlType: 'genericHTML'
    htmlPath: '$(System.DefaultWorkingDirectory)/api-scan-report.html'
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/api-report.json
    artifact: SecurityTest

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/Converted-OWASP-ZAP-Report.xml'
      
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get install xmlstarlet
      echo "##vso[task.setvariable variable=actualThroughput;]$(xmlstarlet sel -t -v '//test-run/@failed' -nl $(System.DefaultWorkingDirectory)/Converted-OWASP-ZAP-Report.xml)"
- task: Bash@3
  inputs:
    script: |
      echo "======= Summary Report ========"
      sudo apt-get install jq
      echo "##vso[task.setvariable variable=inputResultRisk;]$(jq -r '.site | .[] | .alerts | .[] | .riskdesc' $(System.DefaultWorkingDirectory)/api-report.json)"
      echo "==============================="
    targetType: filePath
    filePath: 'zap/check-throughput.sh'
    arguments: '$(actualThroughput) $(expectedThroughput)'
    workingDirectory: zap



  

    